C#_Fundamentals/ProjectZero/StoreWebUI/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using StoreModels;
using SBL;
using StoreWebUI.Models;
using StoreDL;
using Serilog;
using Serilog.Formatting.Json;

namespace StoreWebUI.Controllers
{
    public class CustomerController : Controller
    {
        private IStoreBL _storeBL;
        private RRProject0Context _context;
        public CustomerController(IStoreBL p_storeBL, RRProject0Context p_context)
        {
            _context = p_context;
            _storeBL = p_storeBL;
        }

        public ActionResult Index()
        {
            try
            {
                return View(_storeBL.GetAllCustomers()
                    .Select(cust => new CustomerVM(cust))
                    .ToList());
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Delete(int p_id)
        {
            try
            {
                return View(new CustomerVM(_storeBL.GetCustomerById(p_id)));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Search(string SearchString)
        {
            try
            {
                return View(_context.Customer.Where(x => x.Name == SearchString)
                    .Select(cust => new CustomerVM(cust))
                    .ToList());
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int CustId, IFormCollection collection)
        { 
            Log.Logger = new LoggerConfiguration()
                .Enrich.FromLogContext()
                .WriteTo.File(new JsonFormatter(),"Logs/customerlog.json")
                .CreateLogger();
            try
            {
                Log.Information("Deleting customer");
                Customer toBeDeleted = _storeBL.GetCustomerById(CustId);
                _storeBL.DeleteCustomer(toBeDeleted);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                Log.Information("Deletion Failed");
                return View();
            }
            finally
            {
                Log.CloseAndFlush();
            }
        }

        public ActionResult Login()
        {
            return View();
        }

        public ActionResult Signup()
        {
            return View();
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CustomerVM custVM)
        {
            if (ModelState.IsValid)
            {
                _storeBL.AddCustomer(new Customer()
                {
                    Name = custVM.Name,
                    Address = custVM.Address,
                    Email = custVM.Email
                });

                return RedirectToAction(nameof(Index));
            }

            //Will return back to the create view if the user didn't specify the right input
            return View();
        }

        public ActionResult Edit(int id)
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

C#_Fundamentals/ProjectZero/StoreWebUI/Controllers/OrderController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using StoreModels;
using SBL;
using StoreWebUI.Models;
using Serilog;
using Serilog.Formatting.Json;

namespace StoreWebUI.Controllers
{
    public class OrderController : Controller
    {
        private IStoreBL _storeBL;
        public OrderController(IStoreBL p_storeBL)
        {
            _storeBL = p_storeBL;
        }
        // GET: OrderController
        public ActionResult Index()
        {
            try
            {
                return View(_storeBL.GetAllOrders()
                    .Select(ord => new OrderVM(ord))
                    .ToList());
            }
            catch
            {
                return View();
            }
        }

        public ActionResult StoreOrders(int p_id)
        {
            try
            {
                return View(_storeBL.GetAllStoreOrdersById(p_id)
                    .Select(ord => new OrderVM(ord))
                    .ToList());
            }
            catch
            {
                return View();
            }
        }

        public ActionResult CustomerOrders(int p_id)
        {
            try
            {
                return View(_storeBL.GetAllCustomerOrdersById(p_id)
                    .Select(ord => new OrderVM(ord))
                    .ToList());
            }
            catch
            {
                return View();
            }
        }

        // GET: OrderController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: OrderController/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        // POST: OrderController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(OrderVM ordVM)
        {
            if (ModelState.IsValid)
            {
                _storeBL.PlaceOrders(new Orders()
                {
                    CustId = ordVM.CustId,
                    StoreId = ordVM.StoreId,
                    prodId = ordVM.prodId,
                    Total = ordVM.Total
                });

                return RedirectToAction(nameof(Index));
            }

            //Will return back to the create view if the user didn't specify the right input
            return View();
        }

        public IActionResult SortOrder()
        {
            Log.Logger = new LoggerConfiguration()
                .Enrich.FromLogContext()
                .WriteTo.File(new JsonFormatter(),"Logs/orderlog.json")
                .CreateLogger();
            try
            {
                Log.Information("Sorting Order");
                return View(_storeBL.GetSortOrder()
                    .Select(ord => new OrderVM(ord))
                    .ToList());
            }
            catch
            {
                Log.Fatal("Sorting order Failed");
                return View();
            }
            finally
            {
                Log.CloseAndFlush();
            }
        }


        // GET: OrderController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: OrderController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: OrderController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: OrderController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

C#_Fundamentals/ProjectZero/StoreWebUI/Views/Customer/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model IEnumerable<StoreWebUI.Models.CustomerVM>

<h1> List of Customers</h1>
<div>
    <a class="btn btn-primary text-white" asp-controller="Customer" asp-action="Create">Add Customer</a>
</div>
<br />
<div class="text-sm-left">
    @using (Html.BeginForm("Search","Customer"))
    {
        <p>
            Find by name: @Html.TextBox("SearchString")
            <input type="submit" value="Search" />
        </p>
    }
    @*<a asp-controller="Customer" asp-action="Index"> Click here to search for a customer</a>*@
</div>
<table class="table table-striped table-hover">
    <tr>    
            <th>Customer ID</th>
            <th>Name</th>
            <th>Address</th>
            <th>Email</th>
            <th></th>
    </tr>
        @foreach(CustomerVM item in Model)
        {
    <tr>
        <td>@Html.DisplayFor(modelItem => item.CustId)</td>
        <td>@Html.DisplayFor(modelItem => item.Name)</td>
        <td>@Html.DisplayFor(modelItem => item.Address)</td>
        <td>@Html.DisplayFor(modelItem => item.Email)</td>
        <td>
            <button class="btn btn-danger" style="color: white">
                @Html.ActionLink("Delete", "Delete", new { p_id = item.CustId }, new { @style = "color: white" })
            </button>
            <button class="btn btn-primary" style="color: white">
                @Html.ActionLink("View Orders", "CustomerOrders", "Order", new { p_id = item.CustId }, new { @style = "color: white" })
            </button>
        </td>
    </tr>
            }
</table>

C#_Fundamentals/ProjectZero/StoreWebUI/Views/Customer/Search.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model IEnumerable<StoreWebUI.Models.CustomerVM>

<h1> List of Customers</h1>
<div>
    <a class="btn btn-primary text-white" asp-controller="Customer" asp-action="Create">Add Customer</a>
</div>
<br />
<div class="text-sm-left">
    @using (Html.BeginForm("Search", "Customer"))
    {
<p>
    Find by name: @Html.TextBox("SearchString")
    <input type="submit" value="Search" />
</p>}
</div>
<table class="table table-striped table-hover">
    <tr>
        <th>Customer ID</th>
        <th>Name</th>
        <th>Address</th>
        <th>Email</th>
        <th></th>
    </tr>
    @foreach (CustomerVM item in Model)
    {
<tr>
    <td>@Html.DisplayFor(modelItem => item.CustId)</td>
    <td>@Html.DisplayFor(modelItem => item.Name)</td>
    <td>@Html.DisplayFor(modelItem => item.Address)</td>
    <td>@Html.DisplayFor(modelItem => item.Email)</td>
    <td>
        <button class="btn btn-danger" style="color: white">
            @Html.ActionLink("Delete", "Delete", new { p_id = item.CustId }, new { @style = "color: white" })
        </button>
        <button class="btn btn-primary" style="color: white">
            @Html.ActionLink("View Orders", "CustomerOrders", "Order", new { p_id = item.CustId }, new { @style = "color: white" })
        </button>
    </td>
</tr>            }
</table>